// Code generated by protoc-gen-go.
// source: tdbas.proto
// DO NOT EDIT!

/*
Package tdbas is a generated protocol buffer package.

It is generated from these files:
	tdbas.proto

It has these top-level messages:
	Task
	TaskStatus
*/
package tdbas

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskStatusCode int32

const (
	TaskStatusCode_Unknown TaskStatusCode = 0
	TaskStatusCode_Ok      TaskStatusCode = 1
	TaskStatusCode_Failed  TaskStatusCode = 2
)

var TaskStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}
var TaskStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x TaskStatusCode) String() string {
	return proto.EnumName(TaskStatusCode_name, int32(x))
}
func (TaskStatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Task struct {
	Tracking   string `protobuf:"bytes,1,opt,name=tracking" json:"tracking,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Parameters string `protobuf:"bytes,3,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetTracking() string {
	if m != nil {
		return m.Tracking
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

type TaskStatus struct {
	Message string         `protobuf:"bytes,1,opt,name=Message,json=message" json:"Message,omitempty"`
	Code    TaskStatusCode `protobuf:"varint,2,opt,name=Code,json=code,enum=tdbas.TaskStatusCode" json:"Code,omitempty"`
}

func (m *TaskStatus) Reset()                    { *m = TaskStatus{} }
func (m *TaskStatus) String() string            { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()               {}
func (*TaskStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TaskStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TaskStatus) GetCode() TaskStatusCode {
	if m != nil {
		return m.Code
	}
	return TaskStatusCode_Unknown
}

func init() {
	proto.RegisterType((*Task)(nil), "tdbas.Task")
	proto.RegisterType((*TaskStatus)(nil), "tdbas.TaskStatus")
	proto.RegisterEnum("tdbas.TaskStatusCode", TaskStatusCode_name, TaskStatusCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TdbasService service

type TdbasServiceClient interface {
	CallTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskStatus, error)
}

type tdbasServiceClient struct {
	cc *grpc.ClientConn
}

func NewTdbasServiceClient(cc *grpc.ClientConn) TdbasServiceClient {
	return &tdbasServiceClient{cc}
}

func (c *tdbasServiceClient) CallTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*TaskStatus, error) {
	out := new(TaskStatus)
	err := grpc.Invoke(ctx, "/tdbas.TdbasService/CallTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TdbasService service

type TdbasServiceServer interface {
	CallTask(context.Context, *Task) (*TaskStatus, error)
}

func RegisterTdbasServiceServer(s *grpc.Server, srv TdbasServiceServer) {
	s.RegisterService(&_TdbasService_serviceDesc, srv)
}

func _TdbasService_CallTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TdbasServiceServer).CallTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tdbas.TdbasService/CallTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TdbasServiceServer).CallTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

var _TdbasService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tdbas.TdbasService",
	HandlerType: (*TdbasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTask",
			Handler:    _TdbasService_CallTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tdbas.proto",
}

func init() { proto.RegisterFile("tdbas.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x18, 0x93, 0xfa, 0x22, 0x25, 0x0e, 0x08, 0xa1, 0x07, 0x91, 0x9c, 0x54, 0xa4,
	0x60, 0xbd, 0x7a, 0x2b, 0x78, 0x13, 0xb1, 0xad, 0xde, 0xa7, 0xc9, 0x50, 0x42, 0x92, 0xdd, 0xb2,
	0xbb, 0xea, 0xdf, 0x97, 0x6c, 0x44, 0x23, 0xde, 0xf6, 0xbd, 0xc7, 0x7e, 0x6f, 0x66, 0x90, 0xba,
	0x6a, 0xc7, 0x76, 0x71, 0x30, 0xda, 0x69, 0x3a, 0xf6, 0xa2, 0x78, 0x43, 0xb4, 0x65, 0xdb, 0xd0,
	0x1c, 0x53, 0x67, 0xb8, 0x6c, 0x6a, 0xb5, 0xcf, 0x83, 0xcb, 0xe0, 0xea, 0x64, 0xfd, 0xa3, 0x89,
	0x10, 0x29, 0xee, 0x24, 0x0f, 0xbd, 0xef, 0xdf, 0x74, 0x01, 0x1c, 0xd8, 0x70, 0x27, 0x4e, 0x8c,
	0xcd, 0x8f, 0x7c, 0x32, 0x72, 0x8a, 0x17, 0xa0, 0xe7, 0x6e, 0x1c, 0xbb, 0x77, 0x4b, 0x39, 0x92,
	0x27, 0xb1, 0x96, 0xf7, 0xf2, 0x0d, 0x4f, 0xba, 0x41, 0xd2, 0x35, 0xa2, 0x95, 0xae, 0x06, 0xf6,
	0x6c, 0x79, 0xbe, 0x18, 0x46, 0xfc, 0xfd, 0xda, 0x87, 0xeb, 0xa8, 0xd4, 0x95, 0xdc, 0xdc, 0x61,
	0xf6, 0xd7, 0xa7, 0x14, 0xc9, 0xab, 0x6a, 0x94, 0xfe, 0x54, 0xd9, 0x84, 0x62, 0x84, 0xcf, 0x4d,
	0x16, 0x10, 0x10, 0x3f, 0x72, 0xdd, 0x4a, 0x95, 0x85, 0xcb, 0x07, 0x9c, 0x6e, 0x7b, 0xe0, 0x46,
	0xcc, 0x47, 0x5d, 0x0a, 0xdd, 0x62, 0xba, 0xe2, 0xb6, 0xf5, 0x1b, 0xa7, 0xa3, 0xae, 0xf9, 0xd9,
	0xbf, 0xe2, 0x62, 0xb2, 0x8b, 0xfd, 0xa5, 0xee, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xd9,
	0x68, 0x79, 0x38, 0x01, 0x00, 0x00,
}
